title: Hyein Kim
description: Personal blog
markdown: kramdown

collections:
  blog:
    output: true
    permalink: /abcd/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: blog
    values:
      layout: blog_layout
  - scope:
      path: ""
      type: projects
    values:
      layout: project_layout
